In [59]:
import pandas as pd
data=pd.read_csv("user_positive_games.csv")
data.head()

             steamid     app_id
0  76561197960265841  [1825540]
1  76561197960265890   [201070]
2  76561197960267068  [1677970]
3  76561197960267615    [98900]
4  76561197960268079   [446110]

In [60]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195200 entries, 0 to 195199
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   steamid  195200 non-null  int64
 1   app_id   195200 non-null  object
dtypes: int64(1), object(1)
memory usage: 3.0+ MB

In [61]:
import ast

data['app_id'] = data['app_id'].apply(ast.literal_eval)  # Convert to lists
data = data[data['app_id'].apply(lambda x: len(x) > 3)]  # Filter
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4186 entries, 21 to 195039
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   steamid  4186 non-null   int64
 1   app_id   4186 non-null   object
dtypes: int64(1), object(1)
memory usage: 98.1+ KB

In [62]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules
transactions = data['app_id'].tolist() # Convert the 'app_id' column to a list of transactions

te = TransactionEncoder()
te_ary = te.fit_transform(transactions)
df = pd.DataFrame(te_ary, columns=te.columns_)
df.head()

,20,1250,1520,1670,1700,2270,2280,2360,2370,2390,...,3479150,3479190,3479680,3486980,3505820,3505840,3505850,3505880,3505890,3505910
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [63]:
df.head()

,20,1250,1520,1670,1700,2270,2280,2360,2370,2390,...,3479150,3479190,3479680,3486980,3505820,3505840,3505850,3505880,3505890,3505910
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [66]:
frequent_itemsets = apriori(df, min_support=0.004, use_colnames=True)

rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)

In [67]:
print(rules)

           antecedents         consequents  antecedent support  \
0             (964020)           (1256830)            0.010033
1            (1256830)            (964020)            0.010750
2            (1312060)           (2446710)            0.009078
3            (2446710)           (1312060)            0.011228
4            (1728610)           (2728950)            0.007645
5            (2728950)           (1728610)            0.014095
6            (1828640)           (2446710)            0.009795
7            (2446710)           (1828640)            0.011228
8            (2077060)           (2446710)            0.005495
9            (2446710)           (2077060)            0.011228
10           (2692800)           (3285370)            0.008600
11           (3285370)           (2692800)            0.009317
12           (2692800)           (3313560)            0.008600
13           (3313560)           (2692800)            0.009078
14           (2692800)           (3379650)            0.008600
15           (3379650)           (2692800)            0.010272
16           (3204840)           (3206090)            0.007406
17           (3206090)           (3204840)            0.006689
18           (3204840)           (3285370)            0.007406
19           (3285370)           (3204840)            0.009317
20           (3313560)           (3204840)            0.009078
21           (3204840)           (3313560)            0.007406
22           (3206090)           (3285370)            0.006689
23           (3285370)           (3206090)            0.009317
24           (3313560)           (3206090)            0.009078
25           (3206090)           (3313560)            0.006689
26           (3313560)           (3285370)            0.009078
27           (3285370)           (3313560)            0.009317
28           (3313560)           (3379650)            0.009078
29           (3379650)           (3313560)            0.010272
30  (2692800, 3285370)           (3313560)            0.004778
31  (2692800, 3313560)           (3285370)            0.004778
32  (3313560, 3285370)           (2692800)            0.007645
33           (2692800)  (3313560, 3285370)            0.008600
34           (3285370)  (2692800, 3313560)            0.009317
35           (3313560)  (2692800, 3285370)            0.009078

    consequent support   support  confidence        lift  leverage  conviction
0             0.010750  0.004300    0.428571   39.866667  0.004192    1.731187
1             0.010033  0.004300    0.400000   39.866667  0.004192    1.649944
2             0.011228  0.004778    0.526316   46.875700  0.004676    2.087408
3             0.009078  0.004778    0.425532   46.875700  0.004676    1.724939
4             0.014095  0.004539    0.593750   42.126059  0.004431    2.426844
5             0.007645  0.004539    0.322034   42.126059  0.004431    1.463724
6             0.011228  0.004539    0.463415   41.273482  0.004429    1.842712
7             0.009795  0.004539    0.404255   41.273482  0.004429    1.662131
8             0.011228  0.004300    0.782609   69.702128  0.004238    4.548352
9             0.005495  0.004300    0.382979   69.702128  0.004238    1.611785
10            0.009317  0.004778    0.555556   59.629630  0.004698    2.229037
11            0.008600  0.004778    0.512821   59.629630  0.004698    2.034979
12            0.009078  0.004778    0.555556   61.198830  0.004700    2.229575
13            0.008600  0.004778    0.526316   61.198830  0.004700    2.092955
14            0.010272  0.004778    0.555556   54.082687  0.004689    2.226887
15            0.008600  0.004778    0.465116   54.082687  0.004689    1.853487
16            0.006689  0.005733    0.774194  115.741935  0.005684    4.398949
17            0.007406  0.005733    0.857143  115.741935  0.005684    6.948161
18            0.009317  0.004778    0.645161   69.247312  0.004709    2.791925
19            0.007406  0.004778    0.512821   69.247312  0.004709    2.037431
20            0.007406  0.004300    0.473684   63.962649  0.004233    1.885929
21            0.009078  0.004300    0.580645   63.962649  0.004233    2.362968
22            0.009317  0.004539    0.678571   72.833333  0.004477    3.082126
23            0.006689  0.004539    0.487179   72.833333  0.004477    1.936957
24            0.006689  0.004061    0.447368   66.881579  0.004000    1.797420
25            0.009078  0.004061    0.607143   66.881579  0.004000    2.522347
26            0.009317  0.007645    0.842105   90.385965  0.007560    6.274327
27            0.009078  0.007645    0.820513   90.385965  0.007560    5.520852
28            0.010272  0.004539    0.500000   48.674419  0.004446    1.979455
29            0.009078  0.004539    0.441860   48.674419  0.004446    1.775402
30            0.009078  0.004061    0.850000   93.634211  0.004018    6.606147
31            0.009317  0.004061    0.850000   91.233333  0.004017    6.604555
32            0.008600  0.004061    0.531250   61.772569  0.003995    2.114986
33            0.007645  0.004061    0.472222   61.772569  0.003995    1.880252
34            0.004778  0.004061    0.435897   91.233333  0.004017    1.764257
35            0.004778  0.004061    0.447368   93.634211  0.004018    1.800878

In [70]:
# Sort rules by lift and confidence
best_rules = rules.sort_values(['lift', 'confidence'], ascending=[False, False])

# Print top 10 best rules with their metrics
print("Top 10 Best Association Rules:")
print("\n{:<15} {:<15} {:<10} {:<10} {:<10}".format(
    "Antecedent", "Consequent", "Lift", "Confidence", "Support"))
print("-" * 65)

for index, row in best_rules.head(10).iterrows():
    antecedents = list(row['antecedents'])
    consequents = list(row['consequents'])
    
    print("{:<15} {:<15} {:<10.2f} {:<10.2f} {:<10.4f}".format(
        str(antecedents[0]),
        str(consequents[0]),
        row['lift'],
        row['confidence'],
        row['support']
    ))

Top 10 Best Association Rules:

Antecedent      Consequent      Lift       Confidence Support
-----------------------------------------------------------------
3206090         3204840         115.74     0.86       0.0057
3204840         3206090         115.74     0.77       0.0057
2692800         3313560         93.63      0.85       0.0041
3313560         2692800         93.63      0.45       0.0041
2692800         3285370         91.23      0.85       0.0041
3285370         2692800         91.23      0.44       0.0041
3313560         3285370         90.39      0.84       0.0076
3285370         3313560         90.39      0.82       0.0076
3206090         3285370         72.83      0.68       0.0045
3285370         3206090         72.83      0.49       0.0045

In [16]:
game_data=pd.read_csv("D:\data-mining-hcmiu\game\cleaned_game\steam_game_data_encoded.csv")
game_data.head()

<>:1: DeprecationWarning: invalid escape sequence '\d'
<>:1: DeprecationWarning: invalid escape sequence '\d'
C:\Users\Khoi Dang\AppData\Local\Temp\ipykernel_22904\455950550.py:1: DeprecationWarning: invalid escape sequence '\d'
  game_data=pd.read_csv("D:\data-mining-hcmiu\game\cleaned_game\steam_game_data_encoded.csv")

,app_id,description,price_encoded,release_year_encoded,all_reviews_encoded,all_percent_encoded,all_count_encoded,tags_encoded
0,1769730,dont lose signal get,1,1,1,0,0,0
1,1769740,cubes death dpuzzle game story mode single pla...,1,1,0,0,0,6
2,1769750,autorunner controlled single mouse click level...,1,1,1,0,0,2
3,1769760,walking forest discover bunker entrance andmee...,1,1,1,0,0,6
4,1769780,create graffiti art,1,1,6,2,1,6

In [24]:
import os

# file_path = os.path.join('game', 'steam_game_descriptions_all.csv')
#
# if not os.path.exists(file_path):
#     print('File not found:', os.path.abspath(file_path))
# else:
#     print('File found:', os.path.abspath(file_path))
#     # Read the dataset
#     game_data = pd.read_csv(file_path)
#     print(game_data.head())

file_path1 = r'D:\data-mining-hcmiu\game\steam_game_descriptions_part_1.csv'
file_path2 = r'D:\data-mining-hcmiu\game\steam_game_descriptions_part_2.csv'

game_data = pd.DataFrame()

if os.path.exists(file_path1):
    print('File found:', os.path.abspath(file_path1))
    game_data_1 = pd.read_csv(file_path1)
    game_data = game_data_1
else:
    print('File not found:', os.path.abspath(file_path1))

if os.path.exists(file_path2):
    print('File found:', os.path.abspath(file_path2))
    game_data_2 = pd.read_csv(file_path2)
    game_data = pd.concat([game_data, game_data_2], ignore_index=True)
else:
    print('File not found:', os.path.abspath(file_path2))

if game_data.empty:
    print("Error: No game data loaded.")
else:
    game_data.head()

File found: D:\data-mining-hcmiu\game\steam_game_descriptions_part_1.csv
File found: D:\data-mining-hcmiu\game\steam_game_descriptions_part_2.csv

In [25]:
game_data.head()

,app_id,name,tags,popular_tags,all_reviews,all_percent,all_count,release_date,developer,publisher,price,description
0,1769390,Lack of Water,"Casual,Strategy,Puzzle","Casual,Strategy,Puzzle,Cute,Comedy,Physics,Sin...",1 user reviews,Need more user reviews to generate a score,NaN,1905-07-17,QuickBobber,QuickBobber,$5.99,Lack of water is a puzzle game. You need to di...
1,1769470,Non-Euclidean Chess,"Early Access,Strategy,Chess","Early Access,Strategy,Chess,Battle Royale,Boar...",8 user reviews,Need more user reviews to generate a score,NaN,1905-07-17,Cole Ferguson,Manifold Interactive,$7.99,Non-Euclidean Chess provides a chess engine wi...
2,1769510,FEWAR-DVD,"Arcade,Action Roguelike,Action","Arcade,Action Roguelike,Action,Procedural Gene...",Very Positive,98%,64.0,1905-07-17,dev_dwarf,NaN,Free To Play,A rapid arcade game. Avoid the swords. Find th...
3,1769640,Wilderplace,"Exploration,Minimalist,Isometric","Exploration,Minimalist,Isometric,Turn-Based Ta...",Positive,100%,24.0,1905-07-17,Saman Bemel-Benrud,Saman Bemel-Benrud,$12.99,Wilderplace is a turn-based spatial puzzle gam...
4,1769730,Connection,"Horror,Survival Horror,Psychological Horror","Horror,Survival Horror,Psychological Horror,Fi...",1 user reviews,Need more user reviews to generate a score,NaN,1984-06-01,FTH GAMES,FTH GAMES,$9.99,Don't lose the signal to get out of here.

In [27]:
print(rules.columns)

Index(['antecedents', 'consequents', 'antecedent support',
       'consequent support', 'support', 'confidence', 'lift', 'leverage',
       'conviction', 'Antecedent_Name', 'Consequent_Name'],
      dtype='object')

In [71]:
# Ensure 'app_id' and 'name' columns exist in game_data
if {'app_id', 'name'}.issubset(game_data.columns):
    # Create a dictionary mapping app_id to game name
    app_id_to_name = game_data.set_index('app_id')['name'].to_dict()

    # Replace Antecedent and Consequent IDs with their names
    rules['Antecedent_Name'] = rules['antecedents'].apply(
        lambda x: ', '.join([app_id_to_name.get(int(i), 'Unknown') for i in list(x)]))
    rules['Consequent_Name'] = rules['consequents'].apply(
        lambda x: ', '.join([app_id_to_name.get(int(i), 'Unknown') for i in list(x)]))

    # Display the updated rules with game names
    print(rules[['Antecedent_Name', 'Consequent_Name', 'lift', 'confidence', 'support']])
else:
    print("Error: 'app_id' or 'name' column not found in game_data.")

                     Antecedent_Name                   Consequent_Name  \
0                  Make Your Kingdom                   Shelter Manager
1                    Shelter Manager                 Make Your Kingdom
2                    Zero-G Gunfight                  Cyberside Picnic
3                   Cyberside Picnic                   Zero-G Gunfight
4                Beyond The Darkness                 Potty Knight Saga
5                  Potty Knight Saga               Beyond The Darkness
6                     IllusionCircle                  Cyberside Picnic
7                   Cyberside Picnic                    IllusionCircle
8                              SATUS                  Cyberside Picnic
9                   Cyberside Picnic                             SATUS
10                 I Love You Freddy                     Ancient Ruins
11                     Ancient Ruins                 I Love You Freddy
12                 I Love You Freddy                       Falco Xolon
13                       Falco Xolon                 I Love You Freddy
14                 I Love You Freddy                          Dark PGT
15                          Dark PGT                 I Love You Freddy
16                         Time Over               Arena of the Titans
17               Arena of the Titans                         Time Over
18                         Time Over                     Ancient Ruins
19                     Ancient Ruins                         Time Over
20                       Falco Xolon                         Time Over
21                         Time Over                       Falco Xolon
22               Arena of the Titans                     Ancient Ruins
23                     Ancient Ruins               Arena of the Titans
24                       Falco Xolon               Arena of the Titans
25               Arena of the Titans                       Falco Xolon
26                       Falco Xolon                     Ancient Ruins
27                     Ancient Ruins                       Falco Xolon
28                       Falco Xolon                          Dark PGT
29                          Dark PGT                       Falco Xolon
30  I Love You Freddy, Ancient Ruins                       Falco Xolon
31    I Love You Freddy, Falco Xolon                     Ancient Ruins
32        Falco Xolon, Ancient Ruins                 I Love You Freddy
33                 I Love You Freddy        Falco Xolon, Ancient Ruins
34                     Ancient Ruins    I Love You Freddy, Falco Xolon
35                       Falco Xolon  I Love You Freddy, Ancient Ruins

          lift  confidence   support
0    39.866667    0.428571  0.004300
1    39.866667    0.400000  0.004300
2    46.875700    0.526316  0.004778
3    46.875700    0.425532  0.004778
4    42.126059    0.593750  0.004539
5    42.126059    0.322034  0.004539
6    41.273482    0.463415  0.004539
7    41.273482    0.404255  0.004539
8    69.702128    0.782609  0.004300
9    69.702128    0.382979  0.004300
10   59.629630    0.555556  0.004778
11   59.629630    0.512821  0.004778
12   61.198830    0.555556  0.004778
13   61.198830    0.526316  0.004778
14   54.082687    0.555556  0.004778
15   54.082687    0.465116  0.004778
16  115.741935    0.774194  0.005733
17  115.741935    0.857143  0.005733
18   69.247312    0.645161  0.004778
19   69.247312    0.512821  0.004778
20   63.962649    0.473684  0.004300
21   63.962649    0.580645  0.004300
22   72.833333    0.678571  0.004539
23   72.833333    0.487179  0.004539
24   66.881579    0.447368  0.004061
25   66.881579    0.607143  0.004061
26   90.385965    0.842105  0.007645
27   90.385965    0.820513  0.007645
28   48.674419    0.500000  0.004539
29   48.674419    0.441860  0.004539
30   93.634211    0.850000  0.004061
31   91.233333    0.850000  0.004061
32   61.772569    0.531250  0.004061
33   61.772569    0.472222  0.004061
34   91.233333    0.435897  0.004061
35   93.634211    0.447368  0.004061

In [72]:
# Sort rules by lift and confidence
best_rules = rules.sort_values(['lift', 'confidence'], ascending=[False, False])

# Print top 10 best rules with their metrics
print("Top 10 Best Association Rules:")
print("\n{:<30} {:<30} {:<10} {:<10} {:<10}".format(
    "Antecedent Name", "Consequent Name", "Lift", "Confidence", "Support"))
print("-" * 95)

for index, row in best_rules.head(10).iterrows():
    print("{:<30} {:<30} {:<10.2f} {:<10.2f} {:<10.4f}".format(
        row['Antecedent_Name'],
        row['Consequent_Name'],
        row['lift'],
        row['confidence'],
        row['support']
    ))

Top 10 Best Association Rules:

Antecedent Name                Consequent Name                Lift       Confidence Support
-----------------------------------------------------------------------------------------------
Arena of the Titans            Time Over                      115.74     0.86       0.0057
Time Over                      Arena of the Titans            115.74     0.77       0.0057
I Love You Freddy, Ancient Ruins Falco Xolon                    93.63      0.85       0.0041
Falco Xolon                    I Love You Freddy, Ancient Ruins 93.63      0.45       0.0041
I Love You Freddy, Falco Xolon Ancient Ruins                  91.23      0.85       0.0041
Ancient Ruins                  I Love You Freddy, Falco Xolon 91.23      0.44       0.0041
Falco Xolon                    Ancient Ruins                  90.39      0.84       0.0076
Ancient Ruins                  Falco Xolon                    90.39      0.82       0.0076
Arena of the Titans            Ancient Ruins                  72.83      0.68       0.0045
Ancient Ruins                  Arena of the Titans            72.83      0.49       0.0045